const data={
offerpilot:{n:'01',t:'AI PRODUCT',img:'assets/offerpilot-hero.jpg',alt:'OfferPilot 产品界面',k:'CASE STUDY / OFFERPILOT',h:'从目标岗位，到每天的一步。',l:'一个把职业成长拆成可执行反馈回路的 AI 产品。重点不是聊天，而是让用户持续知道下一步应该做什么。',m:[['我的职责','产品定义 · UX · 前端 · AI 流程'],['关键产出','150+ 岗位 · 17 组 JD 匹配'],['交付状态','Vercel 已上线']],s:[['01 / PROBLEM','求职信息很多，但用户不知道差距在哪里，也不知道今天应该先补什么。'],['02 / SYSTEM','目标设定 → 人岗差距分析 → 成长路线 → 每日测验 → readiness 更新。'],['03 / INTERACTION','用路线、阶段和每日任务把抽象的成长变成可以完成、被记录的动作。'],['04 / BUILD','Next.js、Supabase、DeepSeek。独立完成产品结构、界面和上线。']],a:[['打开线上产品','https://offerpilot-kappa.vercel.app/'],['查看 GitHub','https://github.com/jz-226/offerpilot'],['观看产品录屏','video:assets/offerpilot-showcase.mp4']]},
wind:{n:'02',t:'AI OPERATIONS',img:'assets/6.png',alt:'Marketing Wind Tunnel 决策界面',k:'CASE STUDY / MARKETING WIND TUNNEL',h:'先被用户攻击，再决定上线。',l:'一个给运营人员用的 AI 营销方案碰撞实验室。它把凭感觉上线改成一轮可观察、可回应、可复测的决策过程。',m:[['我的职责','创意 · 产品 · 交互 · 前端 · Prompt'],['关键机制','10 个消费者人格 · 4 个 AI 接口'],['交付状态','AI 开发者大赛 / AI+运营']],s:[['01 / INPUT','运营者输入一份营销方案，系统把它作为待测试的假设。'],['02 / COLLISION','十个消费者人格提出质疑，用户可以拖拽其中一条进入修复舱。'],['03 / EVOLUTION','AI 根据回应给出评分与修改点，生成优化方案，再跑第二轮对比。'],['04 / DECISION','决策台汇总风险等级、最具攻击性的用户和能不能上线的建议。']],a:[['打开线上 Demo','https://www.modelscope.cn/studios/jiangzi226/Marketing-Wind-Tunnel']]},
tutor:{n:'03',t:'MINI PROGRAM',img:'assets/屏幕截图 2026-06-18 003259.jpg',alt:'姜记学情本小程序界面',k:'CASE STUDY / JIANG JI XUEQING BEN',h:'把每节课留下来。',l:'一个给家教老师使用的轻量教学工作台。围绕错题状态流转，帮助老师查看学生情况、安排课程并沉淀课后信息。',m:[['我的职责','需求梳理 · 交互 · 视觉 · 原生开发'],['核心模块','学生档案 · 备课 · 错题 · 总结'],['交付状态','微信小程序已上线']],s:[['01 / CONTEXT','家教工作常分散在聊天记录、纸张和临时笔记里，课后信息很容易丢失。'],['02 / STRUCTURE','首页统计今日课程、待讲错题与周进度，底部导航固定四个最高频入口。'],['03 / STATE','错题从待讲解到已讲解再到已掌握，让学习状态有明确的下一步。'],['04 / BUILD','原生 WXML / WXSS / JS，使用本地存储实现开箱即用。']],a:[['观看创建课程录屏','video:assets/tutor-create-course.mp4']]},
wordquest:{n:'04',t:'H5 GAME',img:'assets/wordquest-cover.png',alt:'单词远征游戏封面',k:'CASE STUDY / WORD QUEST',h:'让背单词，也有一条冒险路线。',l:'一款发布在 TapTap 的 CET-4 四级背词 RPG。用关卡、战斗和成长系统承接词汇学习，让记忆从一次答题变成持续推进的游戏过程。',m:[['我的职责','玩法设计 · 视觉整合 · 前端开发'],['核心机制','词汇战斗 · 六重关卡 · 角色成长'],['交付状态','TapTap H5 已上线']],s:[['01 / CONTEXT','传统背词容易变成孤立的重复练习，用户难以感受到进度和反馈。'],['02 / GAME LOOP','进入关卡 → 通过词汇题战斗 → 获得成长反馈 → 解锁新的区域和挑战。'],['03 / VISUAL','用奇幻地图、角色对战和高辨识度答题面板，把学习目标转成可感知的冒险任务。'],['04 / BUILD','纯前端实现，支持离线运行。']],a:[['打开游戏','game/index.html']]},
before8:{n:'05',t:'GAME DESIGN',img:'assets/before-8am-logo.png',alt:'早八在逃游戏标识',k:'CASE STUDY / BEFORE 8AM',h:'在早八以前，离开这里。',l:'《早八在逃》把熟悉的大学生活区翻转成午夜异常空间：玩家需要探索、搜刮、避开巡夜者，并决定何时带着战利品撤离。',m:[['我的职责','世界观 · 核心循环 · 系统设计 · Unity 开发'],['核心机制','潜行 · 搜刮 · 时间碎片 · 撤离抉择'],['交付状态','TapTap 测试版已上线']],s:[['01 / PREMISE','凌晨 0 点以后，校园不再属于人类。玩家从宿舍翻窗进入，目标是在早八以前找到时间碎片，开启晨门并逃出去。'],['02 / RUN LOOP','翻窗 → 探索与搜刮 → 收集 3 个时间碎片 → 开启晨门 → 立即撤离或继续冒险。'],['03 / STEALTH','巡夜者通过距离、视角和遮挡判断玩家位置。绕墙躲开视线是核心操作。'],['04 / BUILD','基于 Unity 2022.3 LTS 制作，使用 URP、Input System、AI Navigation 与 ScriptableObject 数据驱动。']],a:[['前往 TapTap 测试','https://tap.cn/lRKlLAoXX']]}
};
const $=selector=>document.querySelector(selector),drawer=$('#drawer'),video=$('#video'),player=$('#videoPlayer'),preview=$('#previewImage'),previewVideo=$('#previewVideo'),previewBox=$('#hoverPreview');let hidePreviewTimer;
function closeAll(){drawer.classList.remove('open');video.classList.remove('open');player.pause();player.removeAttribute('src');document.body.classList.remove('lock')}
function positionPreview(event){const width=previewBox.offsetWidth||300,height=previewBox.offsetHeight||280,mouseX=event?.clientX??window.innerWidth*.7,mouseY=event?.clientY??window.innerHeight*.5;const x=Math.min(window.innerWidth-width-24,Math.max(window.innerWidth*.63,mouseX+26));const y=Math.min(window.innerHeight-height-24,Math.max(24,mouseY-height*.42));previewBox.style.transform=`translate3d(${x}px,${y}px,0) scale(1)`}function showImage(row,event){window.clearTimeout(hidePreviewTimer);positionPreview(event);previewBox.classList.add('visible');const source=row.dataset.previewVideo;if(source){previewVideo.src=source;previewVideo.hidden=false;previewVideo.setAttribute('aria-hidden','false');preview.hidden=true;previewVideo.play().catch(()=>{})}else{previewVideo.pause();previewVideo.removeAttribute('src');previewVideo.hidden=true;previewVideo.setAttribute('aria-hidden','true');preview.hidden=false;preview.src=row.dataset.image;preview.alt=row.dataset.alt}}function hidePreview(){hidePreviewTimer=window.setTimeout(()=>{previewVideo.pause();previewBox.classList.remove('visible');previewBox.style.transform='translate3d(-9999px,-9999px,0) scale(.95)'},90)}
function openCase(key){const d=data[key];$('#drawerCount').textContent=d.n;$('#drawerType').textContent=d.t;$('#drawerImage').src=d.img;$('#drawerImage').alt=d.alt;$('#drawerKicker').textContent=d.k;$('#drawerTitle').textContent=d.h;$('#drawerLead').textContent=d.l;$('#drawerMeta').innerHTML=d.m.map(item=>`<span><b>${item[0]}</b>${item[1]}</span>`).join('');$('#drawerSections').innerHTML=d.s.map(item=>`<section><h3>${item[0]}</h3><p>${item[1]}</p></section>`).join('');$('#drawerLinks').innerHTML=d.a.map(item=>item[1].startsWith('video:')?`<button data-video="${item[1].slice(6)}">${item[0]} ↗</button>`:`<a target="_blank" rel="noreferrer" href="${item[1]}">${item[0]} ↗</a>`).join('');drawer.classList.add('open');document.body.classList.add('lock');$('#close').focus();document.querySelectorAll('[data-video]').forEach(button=>button.onclick=()=>{player.src=button.dataset.video;video.classList.add('open');player.play().catch(()=>{})})}
document.querySelectorAll('.project-row').forEach(row=>{row.addEventListener('mouseenter',event=>showImage(row,event));row.addEventListener('mousemove',positionPreview);row.addEventListener('mouseleave',hidePreview);row.addEventListener('focus',event=>showImage(row,event));row.addEventListener('blur',hidePreview);row.addEventListener('click',()=>openCase(row.dataset.case))});
$('#close').onclick=closeAll;$('#videoClose').onclick=closeAll;document.addEventListener('keydown',event=>{if(event.key==='Escape')closeAll()});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(element=>observer.observe(element));
